GET http://localhost:5031/examenes

###
GET http://localhost:5031/examenes/3

###
POST http://localhost:5031/examenes
Content-Type: application/json

{
    "nombre": "Jacinto",
    "descripcion": "Recepcion"
}

###
PUT http://localhost:5031/examenes/1
Content-Type: application/json

{
    "nombre": "Patricio",
    "descripcion": "Guardia"
}

###
DELETE http://localhost:5031/examenes/3